### ISSUE TITLE
Question about the future.

### ISSUE THREAD

**Issue by juliolitwin** [sebastian-heinz/Arrowgene.ENet#1]
Yo,

Do you still intend to continue the project? It's a great project, there are only wrappers.
Regards.

**Comment by sebastian-heinz** [comment]
HI, I started this project as a need to be able to easly use Enet in .netCore across osx/unix/win . But at the moment I don't have that need anymore (I have been looking a bit into KCP protocol, which seems a bit simpler).

Enet is quite complex I'd say and this project is still far away from completion. 

I'm sorry but at the moment I do not have the need or time to continue this project.
